# Alacritty configuration file

# Font configuration
[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" } # Replace with your chosen Nerd Font
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }
bold_italic = { family = "JetBrainsMono Nerd Font", style = "Bold Italic" }
size = 12.0 # Adjust font size as needed

# Window properties
[window]
dimensions = { columns = 120, lines = 30 } # Set initial window size
startup_mode = "Windowed" # Or "Maximized", "Fullscreen"
decorations = "Full" # Or "None" if you prefer minimal window decorations
padding = { x = 8, y = 8 } # Add some padding around the terminal content

# Cursor settings
[cursor]
style = { shape = "Block", blinking = "On" }

# Selection
[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

# Live reload config when file changes
[debug]
log_level = "Warn"
render_timer = false
print_events = false

# Enable dim_transparent option to make background darker when not active
# [env]
# TERM = "xterm-256color" # Often set for better compatibility, though alacritty sets its own

# Key bindings (example of a custom binding)
# [keyboard]
# bindings = [
#     { key = "Space", mods = "Control", action = "ToggleFullscreen" },
# ]
